/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as MockIndexRouteImport } from './routes/mock.index'
import { Route as BankIndexRouteImport } from './routes/bank.index'
import { Route as ReviewVocabularyRouteImport } from './routes/review.vocabulary'
import { Route as ReviewMistakesRouteImport } from './routes/review.mistakes'
import { Route as ReviewFlashcardsRouteImport } from './routes/review.flashcards'
import { Route as MockFullRouteImport } from './routes/mock.full'
import { Route as MockDrillRouteImport } from './routes/mock.drill'
import { Route as BankProRouteImport } from './routes/bank.pro'
import { Route as BankPartIndexRouteImport } from './routes/bank.$part.index'
import { Route as BankPartTopicIndexRouteImport } from './routes/bank.$part.$topic.index'
import { Route as BankPartTopicQuestionIdRouteImport } from './routes/bank.$part.$topic.$questionId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewVocabularyRoute = ReviewVocabularyRouteImport.update({
  id: '/review/vocabulary',
  path: '/review/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewMistakesRoute = ReviewMistakesRouteImport.update({
  id: '/review/mistakes',
  path: '/review/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewFlashcardsRoute = ReviewFlashcardsRouteImport.update({
  id: '/review/flashcards',
  path: '/review/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const MockFullRoute = MockFullRouteImport.update({
  id: '/mock/full',
  path: '/mock/full',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDrillRoute = MockDrillRouteImport.update({
  id: '/mock/drill',
  path: '/mock/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const BankProRoute = BankProRouteImport.update({
  id: '/bank/pro',
  path: '/bank/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPartIndexRoute = BankPartIndexRouteImport.update({
  id: '/bank/$part/',
  path: '/bank/$part/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPartTopicIndexRoute = BankPartTopicIndexRouteImport.update({
  id: '/bank/$part/$topic/',
  path: '/bank/$part/$topic/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPartTopicQuestionIdRoute = BankPartTopicQuestionIdRouteImport.update({
  id: '/bank/$part/$topic/$questionId',
  path: '/bank/$part/$topic/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/bank/pro': typeof BankProRoute
  '/mock/drill': typeof MockDrillRoute
  '/mock/full': typeof MockFullRoute
  '/review/flashcards': typeof ReviewFlashcardsRoute
  '/review/mistakes': typeof ReviewMistakesRoute
  '/review/vocabulary': typeof ReviewVocabularyRoute
  '/bank/': typeof BankIndexRoute
  '/mock/': typeof MockIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/bank/$part/': typeof BankPartIndexRoute
  '/bank/$part/$topic/$questionId': typeof BankPartTopicQuestionIdRoute
  '/bank/$part/$topic/': typeof BankPartTopicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/bank/pro': typeof BankProRoute
  '/mock/drill': typeof MockDrillRoute
  '/mock/full': typeof MockFullRoute
  '/review/flashcards': typeof ReviewFlashcardsRoute
  '/review/mistakes': typeof ReviewMistakesRoute
  '/review/vocabulary': typeof ReviewVocabularyRoute
  '/bank': typeof BankIndexRoute
  '/mock': typeof MockIndexRoute
  '/review': typeof ReviewIndexRoute
  '/bank/$part': typeof BankPartIndexRoute
  '/bank/$part/$topic/$questionId': typeof BankPartTopicQuestionIdRoute
  '/bank/$part/$topic': typeof BankPartTopicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversation': typeof ConversationRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/bank/pro': typeof BankProRoute
  '/mock/drill': typeof MockDrillRoute
  '/mock/full': typeof MockFullRoute
  '/review/flashcards': typeof ReviewFlashcardsRoute
  '/review/mistakes': typeof ReviewMistakesRoute
  '/review/vocabulary': typeof ReviewVocabularyRoute
  '/bank/': typeof BankIndexRoute
  '/mock/': typeof MockIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/bank/$part/': typeof BankPartIndexRoute
  '/bank/$part/$topic/$questionId': typeof BankPartTopicQuestionIdRoute
  '/bank/$part/$topic/': typeof BankPartTopicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversation'
    | '/practice'
    | '/pricing'
    | '/bank/pro'
    | '/mock/drill'
    | '/mock/full'
    | '/review/flashcards'
    | '/review/mistakes'
    | '/review/vocabulary'
    | '/bank/'
    | '/mock/'
    | '/review/'
    | '/bank/$part/'
    | '/bank/$part/$topic/$questionId'
    | '/bank/$part/$topic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversation'
    | '/practice'
    | '/pricing'
    | '/bank/pro'
    | '/mock/drill'
    | '/mock/full'
    | '/review/flashcards'
    | '/review/mistakes'
    | '/review/vocabulary'
    | '/bank'
    | '/mock'
    | '/review'
    | '/bank/$part'
    | '/bank/$part/$topic/$questionId'
    | '/bank/$part/$topic'
  id:
    | '__root__'
    | '/'
    | '/conversation'
    | '/practice'
    | '/pricing'
    | '/bank/pro'
    | '/mock/drill'
    | '/mock/full'
    | '/review/flashcards'
    | '/review/mistakes'
    | '/review/vocabulary'
    | '/bank/'
    | '/mock/'
    | '/review/'
    | '/bank/$part/'
    | '/bank/$part/$topic/$questionId'
    | '/bank/$part/$topic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationRoute: typeof ConversationRoute
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  BankProRoute: typeof BankProRoute
  MockDrillRoute: typeof MockDrillRoute
  MockFullRoute: typeof MockFullRoute
  ReviewFlashcardsRoute: typeof ReviewFlashcardsRoute
  ReviewMistakesRoute: typeof ReviewMistakesRoute
  ReviewVocabularyRoute: typeof ReviewVocabularyRoute
  BankIndexRoute: typeof BankIndexRoute
  MockIndexRoute: typeof MockIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  BankPartIndexRoute: typeof BankPartIndexRoute
  BankPartTopicQuestionIdRoute: typeof BankPartTopicQuestionIdRoute
  BankPartTopicIndexRoute: typeof BankPartTopicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/vocabulary': {
      id: '/review/vocabulary'
      path: '/review/vocabulary'
      fullPath: '/review/vocabulary'
      preLoaderRoute: typeof ReviewVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/mistakes': {
      id: '/review/mistakes'
      path: '/review/mistakes'
      fullPath: '/review/mistakes'
      preLoaderRoute: typeof ReviewMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/flashcards': {
      id: '/review/flashcards'
      path: '/review/flashcards'
      fullPath: '/review/flashcards'
      preLoaderRoute: typeof ReviewFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/full': {
      id: '/mock/full'
      path: '/mock/full'
      fullPath: '/mock/full'
      preLoaderRoute: typeof MockFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/drill': {
      id: '/mock/drill'
      path: '/mock/drill'
      fullPath: '/mock/drill'
      preLoaderRoute: typeof MockDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/pro': {
      id: '/bank/pro'
      path: '/bank/pro'
      fullPath: '/bank/pro'
      preLoaderRoute: typeof BankProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/$part/': {
      id: '/bank/$part/'
      path: '/bank/$part'
      fullPath: '/bank/$part/'
      preLoaderRoute: typeof BankPartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/$part/$topic/': {
      id: '/bank/$part/$topic/'
      path: '/bank/$part/$topic'
      fullPath: '/bank/$part/$topic/'
      preLoaderRoute: typeof BankPartTopicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/$part/$topic/$questionId': {
      id: '/bank/$part/$topic/$questionId'
      path: '/bank/$part/$topic/$questionId'
      fullPath: '/bank/$part/$topic/$questionId'
      preLoaderRoute: typeof BankPartTopicQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationRoute: ConversationRoute,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  BankProRoute: BankProRoute,
  MockDrillRoute: MockDrillRoute,
  MockFullRoute: MockFullRoute,
  ReviewFlashcardsRoute: ReviewFlashcardsRoute,
  ReviewMistakesRoute: ReviewMistakesRoute,
  ReviewVocabularyRoute: ReviewVocabularyRoute,
  BankIndexRoute: BankIndexRoute,
  MockIndexRoute: MockIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  BankPartIndexRoute: BankPartIndexRoute,
  BankPartTopicQuestionIdRoute: BankPartTopicQuestionIdRoute,
  BankPartTopicIndexRoute: BankPartTopicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
